title: LECHAE's
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://lechae.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: LECHAE # add your name
author-img: profile-img.jpg # add your photo
about-author: space for recording</br>many things</br>(especially programming) # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lechae # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: lechae55@gmail.com # add your Email address

# Disqus
discus-identifier: lechae # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
